#!/usr/bin/env bash

set -e

if which docker &> /dev/null ; then
    if [ "$(git diff --shortstat 2> /dev/null)" == "" ] ; then
        if git describe --tags --exact-match HEAD &> /dev/null ; then
            LATEST="yes"
        fi
        if [ -z "$LATEST" ] ; then
            VSN=$(docker run -v "$(pwd):/app" otakup0pe/avakas show /app --pre-build)
        else
            VSN=$(docker run -v "$(pwd):/app" otakup0pe/avakas show /app)
        fi
    else
        VSN="${USER}-${RANDOM}"
    fi
else
    echo "Unable to determine version"
    exit 1
fi

CONTAINER="otakup0pe/tiddlywiki"
[ ! -z "$VSN" ]
docker build \
       --build-arg "VERSION=${VSN}" \
       -t "${CONTAINER}:${VSN}" .

if [ ! -z "$LATEST" ] ; then
    docker tag "${CONTAINER}:${VSN}" "${CONTAINER}:latest"
fi
